services:
  db:
    image: postgres:15
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rest:
    restart: on-failure
    build:
      dockerfile: ./docker/rest.dockerfile
      context: .
    entrypoint: python -m industry_game
    ports:
      - 8000:8000
    environment:
      APP_API_HOST: 0.0.0.0
      APP_API_PORT: 8000

      APP_PG_DSN: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      APP_POOL_SIZE: 8

      APP_LOG_LEVEL: info
      APP_LOG_FORMAT: plain

      APP_SECRET: $APP_SECRET
      APP_PRIVATE_KEY: $APP_PRIVATE_KEY

  frontend:
    restart: on-failure
    build:
      dockerfile: ./docker/frontend.dockerfile
      context: .
      args:
        BASE_URL: https://vk.com
    ports:
      - 80:80
      - 443:443

volumes:
  postgres_data:
    driver: local
